### ISSUE TITLE
RethinkDBDash definitions

### ISSUE THREAD

**Issue by ColonelBundy** [niieani/rethinkdb-typescript-definition#1]
These are not complete right?

**Comment by niieani** [comment]
RethinkDBDash definitions are complete, but they are only an extension to RethinkDB definitions, which also are pretty much are complete. 
However, we are having a debate on simplifying some finer implementation points.
Take a look here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4551
Feel free to contribute to the debate. The main problem is lack of certain features in TypeScript that would allow seamless flow of the types between methods.

**Comment by ColonelBundy** [comment]
I see... well I got several errors with the dash definitions and I didn't really look into it much as I'm in the process converting my project into typescript.

```
Module 'rethinkdb' has no exported member 'RInterface'.at line 70 col 53
```

And

```
Cannot find name 'RconnectionInterface'
```

Just by taking a quick look at these two definition files I don't understand where these interface's are defined. Could you please clear this up?

As I'm quite new to typescript but a long time C# nerd I will definitely contribute to debate.

**Comment by niieani** [comment]
Ah, sorry - the rethinkdbdash files had old interface names. I've pushed an
update, try now.

**Comment by ColonelBundy** [comment]
thank you very much.
